import * as stylex from '@stylexjs/stylex'
import { colors, elevation, fonts, radii, space } from '../lib/theme/tokens.stylex'

export const styles = stylex.create({
  shell: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
    boxSizing: 'border-box',
    backgroundColor: colors.bgSubtle,
    color: colors.fg,
  },
  header: {
    flexShrink: 0,
    position: 'sticky' as const,
    top: 0,
    zIndex: 50,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: space.lg,
    paddingBlock: '12px',
    paddingInline: `clamp(${space.lg}, 4vw, 32px)`,
    backgroundColor: colors.bg,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: colors.border,
    boxShadow: [
      '0 1px 0 rgba(15, 15, 22, 0.04)',
      `inset 0 -3px 0 0 ${colors.accent}`,
    ].join(', '),
  },
  brandRow: {
    display: 'flex',
    alignItems: 'center',
    gap: space.md,
    minWidth: 0,
  },
  logoMark: {
    flexShrink: 0,
    width: '38px',
    height: '38px',
    borderRadius: radii.md,
    backgroundColor: colors.accent,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: fonts.sans,
    fontSize: '0.875rem',
    fontWeight: 700,
    letterSpacing: '-0.06em',
    color: colors.accentFg,
    textDecoration: 'none',
    boxShadow: `0 2px 8px ${colors.accentMuted}`,
    transitionProperty: 'transform, box-shadow',
    transitionDuration: '0.18s',
    ':hover': {
      transform: 'translateY(-1px)',
      boxShadow: `0 4px 14px ${colors.accentMuted}`,
    },
    '@media (prefers-reduced-motion: reduce)': {
      transitionDuration: '0.01ms',
      ':hover': {
        transform: 'none',
      },
    },
  },
  brandBlock: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '2px',
    minWidth: 0,
  },
  brand: {
    fontFamily: fonts.sans,
    fontSize: '1.0625rem',
    fontWeight: 700,
    letterSpacing: '-0.035em',
    color: colors.fg,
    textDecoration: 'none',
    lineHeight: 1.2,
  },
  brandSub: {
    fontFamily: fonts.sans,
    fontSize: '0.625rem',
    fontWeight: 600,
    color: colors.fgSubtle,
    letterSpacing: '0.14em',
    textTransform: 'uppercase' as const,
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: space.sm,
    flexWrap: 'wrap' as const,
  },
  headerLink: {
    fontFamily: fonts.sans,
    fontSize: '0.8125rem',
    fontWeight: 600,
    color: colors.fgMuted,
    textDecoration: 'none',
    paddingBlock: '8px',
    paddingInline: space.md,
    borderRadius: radii.md,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    transitionProperty: 'color, background-color, border-color',
    transitionDuration: '0.14s',
    ':hover': {
      color: colors.fg,
      backgroundColor: colors.bgSubtle,
      borderColor: colors.border,
    },
  },
  body: {
    flex: 1,
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr)',
    minHeight: 0,
    '@media (min-width: 900px)': {
      gridTemplateColumns: 'minmax(248px, 288px) minmax(0, 1fr)',
    },
  },
  sidebar: {
    paddingBlock: space.xl,
    paddingInline: `clamp(${space.md}, 3vw, ${space.lg})`,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: colors.border,
    backgroundColor: colors.bgSubtle,
    boxSizing: 'border-box',
    '@media (min-width: 900px)': {
      borderBottomWidth: 0,
      borderRightWidth: 1,
      borderRightStyle: 'solid',
      borderRightColor: colors.border,
      position: 'sticky' as const,
      top: 0,
      alignSelf: 'start',
      maxHeight: '100vh',
      overflowY: 'auto' as const,
    },
  },
  navLabel: {
    fontFamily: fonts.sans,
    fontSize: '0.625rem',
    fontWeight: 700,
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
    color: colors.fgSubtle,
    marginBottom: space.sm,
    marginTop: space.xl,
    paddingInline: space.sm,
  },
  navLabelFirst: {
    marginTop: 0,
  },
  navLink: {
    display: 'block',
    fontFamily: fonts.sans,
    fontSize: '0.8125rem',
    fontWeight: 500,
    color: colors.fgMuted,
    textDecoration: 'none',
    paddingBlock: '9px',
    paddingInline: space.md,
    borderRadius: radii.md,
    marginBottom: '3px',
    transitionProperty: 'color, background-color, box-shadow',
    transitionDuration: '0.14s',
    ':hover': {
      color: colors.fg,
      backgroundColor: colors.neutralMuted,
    },
  },
  navLinkActive: {
    color: colors.accent,
    fontWeight: 700,
    backgroundColor: colors.bg,
    boxShadow: elevation.card,
  },
  main: {
    minWidth: 0,
    overflowX: 'hidden' as const,
    overflowY: 'auto' as const,
    backgroundColor: colors.bgSubtle,
    paddingBlock: space.md,
    paddingInline: space.sm,
    boxSizing: 'border-box',
    '@media (min-width: 900px)': {
      paddingBlock: space.xl,
      paddingInline: space.lg,
    },
  },
  mainInner: {
    maxWidth: 'min(44rem, 100%)',
    marginInline: 'auto',
    paddingBlock: `clamp(${space.xl}, 4vw, 40px)`,
    paddingInline: `clamp(${space.lg}, 3vw, ${space.xl})`,
    boxSizing: 'border-box',
    minHeight: 'min(100%, 100%)',
    backgroundColor: colors.bg,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    boxShadow: elevation.card,
  },
})
