import * as stylex from '@stylexjs/stylex'
import { colors, fonts, radii, space } from '../lib/theme/tokens.stylex'

export const prose = stylex.create({
  article: {
    maxWidth: '100%',
    marginInline: 0,
    paddingInline: 0,
    paddingBlock: 0,
    boxSizing: 'border-box',
  },
  h1: {
    fontFamily: fonts.serif,
    fontSize: 'clamp(2.125rem, 4.5vw, 2.75rem)',
    fontWeight: 700,
    letterSpacing: '-0.025em',
    lineHeight: 1.12,
    marginTop: 0,
    marginBottom: space.lg,
    color: colors.fg,
    paddingBottom: space.md,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: colors.border,
  },
  h2: {
    fontFamily: fonts.sans,
    fontSize: '0.8125rem',
    fontWeight: 700,
    letterSpacing: '0.06em',
    textTransform: 'uppercase' as const,
    lineHeight: 1.4,
    color: colors.accent,
    marginTop: '3rem',
    marginBottom: space.md,
    paddingBottom: 0,
    borderBottomWidth: 0,
  },
  /** First section after intro (Import) — tighter top spacing */
  h2First: {
    marginTop: space.lg,
  },
  h3: {
    fontFamily: fonts.sans,
    fontSize: '1.0625rem',
    fontWeight: 700,
    letterSpacing: '-0.02em',
    color: colors.fg,
    marginTop: space.xl,
    marginBottom: space.sm,
  },
  p: {
    fontFamily: fonts.serif,
    fontSize: '1.0625rem',
    lineHeight: 1.75,
    color: colors.fgMuted,
    marginTop: 0,
    marginBottom: space.md,
  },
  ul: {
    fontFamily: fonts.serif,
    fontSize: '1.0625rem',
    lineHeight: 1.68,
    color: colors.fgMuted,
    marginBottom: space.md,
    paddingInlineStart: space.xl,
  },
  li: {
    marginBottom: space.xs,
  },
  inlineCode: {
    fontFamily: fonts.mono,
    fontSize: '0.82em',
    fontWeight: 500,
    paddingInline: '7px',
    paddingBlock: '3px',
    borderRadius: radii.sm,
    backgroundColor: colors.accentMuted,
    color: colors.fg,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
  },
  lead: {
    fontFamily: fonts.serif,
    fontSize: '1.125rem',
    lineHeight: 1.72,
    color: colors.fgMuted,
    marginBottom: space.xl,
    paddingBlock: space.lg,
    paddingInline: space.lg,
    borderRadius: radii.md,
    backgroundColor: colors.bgSubtle,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    boxShadow: `inset 3px 0 0 0 ${colors.accent}`,
  },
  link: {
    fontFamily: fonts.sans,
    fontSize: 'inherit',
    fontWeight: 600,
    color: colors.accent,
    textDecoration: 'none',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: colors.accentMuted,
    transitionProperty: 'color, border-color',
    transitionDuration: '0.12s',
    ':hover': {
      color: colors.fg,
      borderBottomColor: colors.fg,
    },
  },
})
