import * as stylex from '@stylexjs/stylex'
import { colors, elevation, fonts, radii, space } from '../theme/tokens.stylex'

const panelIn = stylex.keyframes({
  from: {
    opacity: 0,
    transform: 'translateY(-6px) scale(0.98)',
  },
  to: {
    opacity: 1,
    transform: 'translateY(0) scale(1)',
  },
})

const panelInReduced = stylex.keyframes({
  from: { opacity: 0 },
  to: { opacity: 1 },
})

const spin = stylex.keyframes({
  to: { transform: 'rotate(360deg)' },
})

export const styles = stylex.create({
  field: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    width: '100%',
    boxSizing: 'border-box',
  },
  container: {
    position: 'relative',
    width: '100%',
  },
  /** Trigger + listbox wrapper — click-outside target */
  control: {
    position: 'relative',
    width: '100%',
  },
  trigger: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: space.sm,
    width: '100%',
    boxSizing: 'border-box',
    fontFamily: fonts.sans,
    fontSize: '0.9375rem',
    lineHeight: 1.4,
    textAlign: 'left' as const,
    color: colors.fg,
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.inputBorder,
    borderRadius: radii.md,
    paddingBlock: space.sm,
    paddingInline: space.md,
    outlineStyle: 'none',
    cursor: 'pointer',
    touchAction: 'manipulation',
    userSelect: 'none',
    WebkitTapHighlightColor: 'transparent',
    boxShadow: [
      elevation.input,
      `inset 0 1px 0 rgba(255,255,255,0.04)`,
    ].join(', '),
    backgroundImage: `linear-gradient(180deg, ${colors.bgElevated} 0%, ${colors.inputBg} 100%)`,
    transitionProperty: 'border-color, box-shadow, transform',
    transitionDuration: '0.14s',
    transitionTimingFunction: 'ease',
    transformOrigin: 'center',
    ':hover': {
      borderColor: colors.borderStrong,
    },
    ':focus-visible': {
      borderColor: colors.accent,
      boxShadow: `0 0 0 3px ${colors.focusRing}, ${elevation.input}`,
    },
    ':active:not(:disabled)': {
      transform: 'scale(0.985)',
    },
    ':disabled': {
      opacity: 0.55,
      cursor: 'not-allowed',
      transform: 'none',
    },
    '@media (prefers-reduced-motion: reduce)': {
      ':active': {
        transform: 'none',
      },
    },
  },
  triggerOpen: {
    borderColor: colors.accent,
    boxShadow: `0 0 0 1px ${colors.accentMuted}, 0 0 0 3px ${colors.focusRing}`,
  },
  triggerError: {
    borderColor: colors.danger,
    ':focus-visible': {
      borderColor: colors.danger,
      boxShadow: `0 0 0 3px ${colors.dangerMuted}`,
    },
  },
  triggerMain: {
    display: 'flex',
    alignItems: 'center',
    gap: space.xs,
    flex: 1,
    minWidth: 0,
  },
  triggerLabel: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  triggerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: space.xs,
    flexShrink: 0,
  },
  clearBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '1.75rem',
    height: '1.75rem',
    marginInline: '-4px',
    padding: 0,
    borderWidth: 0,
    borderStyle: 'none',
    borderRadius: radii.sm,
    backgroundColor: 'transparent',
    color: colors.fgMuted,
    cursor: 'pointer',
    outlineStyle: 'none',
    transitionProperty: 'background-color, color',
    transitionDuration: '0.12s',
    ':hover': {
      backgroundColor: colors.bgSubtle,
      color: colors.fg,
    },
    ':focus-visible': {
      boxShadow: `0 0 0 2px ${colors.focusRing}`,
    },
  },
  spinner: {
    width: '1.125rem',
    height: '1.125rem',
    flexShrink: 0,
    color: colors.fgMuted,
    animationName: spin,
    animationDuration: '0.7s',
    animationIterationCount: 'infinite',
    animationTimingFunction: 'linear',
    '@media (prefers-reduced-motion: reduce)': {
      animationName: 'none',
    },
  },
  filterWrap: {
    paddingBlock: space.xs,
    paddingInline: space.sm,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: colors.border,
    backgroundColor: colors.bgSubtle,
  },
  filterInput: {
    display: 'block',
    width: '100%',
    boxSizing: 'border-box',
    fontFamily: fonts.sans,
    fontSize: '0.8125rem',
    lineHeight: 1.4,
    color: colors.fg,
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.inputBorder,
    borderRadius: radii.sm,
    paddingBlock: '6px',
    paddingInline: space.sm,
    outlineStyle: 'none',
    ':focus-visible': {
      borderColor: colors.accent,
      boxShadow: `0 0 0 2px ${colors.focusRing}`,
    },
  },
  emptyFilter: {
    paddingBlock: space.md,
    paddingInline: space.md,
    fontFamily: fonts.sans,
    fontSize: '0.8125rem',
    color: colors.fgMuted,
    textAlign: 'center' as const,
  },
  panelFooter: {
    paddingBlock: space.sm,
    paddingInline: space.md,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    backgroundColor: colors.bgSubtle,
    fontFamily: fonts.sans,
    fontSize: '0.8125rem',
    color: colors.fgMuted,
  },
  placeholder: {
    color: colors.placeholder,
  },
  iconWrap: {
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '1.25rem',
    height: '1.25rem',
    color: colors.fgSubtle,
    transitionProperty: 'transform, color',
    transitionDuration: '0.2s',
    transitionTimingFunction: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
  },
  iconOpen: {
    transform: 'rotate(180deg)',
    color: colors.accent,
  },
  dropdown: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '100%',
    marginTop: space.xs,
    zIndex: 100,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    backgroundColor: colors.bgElevated,
    boxShadow: elevation.cardHover,
    overflow: 'hidden',
    transformOrigin: 'top center',
    '@media (prefers-reduced-motion: no-preference)': {
      animationName: panelIn,
      animationDuration: '0.22s',
      animationFillMode: 'both' as const,
      animationTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)',
    },
    '@media (prefers-reduced-motion: reduce)': {
      animationName: panelInReduced,
      animationDuration: '0.12s',
      animationFillMode: 'both' as const,
    },
  },
  list: {
    listStyle: 'none',
    margin: 0,
    padding: space.xs,
    maxHeight: 'min(280px, 50vh)',
    overflowY: 'auto' as const,
    boxSizing: 'border-box',
  },
  option: {
    display: 'flex',
    alignItems: 'center',
    gap: space.sm,
    width: '100%',
    boxSizing: 'border-box',
    fontFamily: fonts.sans,
    fontSize: '0.875rem',
    lineHeight: 1.35,
    color: colors.fg,
    textAlign: 'left' as const,
    paddingBlock: space.sm,
    paddingInline: space.md,
    borderWidth: 0,
    borderRadius: radii.sm,
    backgroundColor: 'transparent',
    cursor: 'pointer',
    outlineStyle: 'none',
    transitionProperty: 'background-color, color, transform',
    transitionDuration: '0.1s',
    ':hover': {
      backgroundColor: colors.bgSubtle,
    },
  },
  optionHighlighted: {
    backgroundColor: colors.accentMuted,
    color: colors.fg,
  },
  optionSelected: {
    fontWeight: 600,
    color: colors.accent,
  },
  optionDisabled: {
    opacity: 0.45,
    cursor: 'not-allowed',
    ':hover': {
      backgroundColor: 'transparent',
    },
  },
  check: {
    flexShrink: 0,
    width: '1rem',
    height: '1rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: colors.accent,
    opacity: 0,
  },
  checkVisible: {
    opacity: 1,
  },
  optionLabel: {
    flex: 1,
    minWidth: 0,
  },
  message: {
    marginTop: space.xs,
  },
})
