import * as stylex from '@stylexjs/stylex'
import { colors, radii, space } from '../theme/tokens.stylex'

export const styles = stylex.create({
  triggerMain: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    alignItems: 'center',
    gap: space.xs,
    flex: 1,
    minWidth: 0,
    minHeight: '1.25rem',
  },
  placeholder: {
    color: colors.placeholder,
    fontSize: '0.9375rem',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    flex: 1,
    minWidth: 0,
  },
  summary: {
    fontSize: '0.9375rem',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    flex: 1,
    minWidth: 0,
  },
  chip: {
    display: 'inline-flex',
    alignItems: 'center',
    maxWidth: '100%',
    gap: '4px',
    paddingBlock: '2px',
    paddingInline: space.sm,
    borderRadius: radii.sm,
    backgroundColor: colors.accentMuted,
    color: colors.fg,
    fontSize: '0.8125rem',
    fontWeight: 500,
    lineHeight: 1.3,
  },
  chipLabel: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    minWidth: 0,
  },
  chipRemove: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    width: '1.125rem',
    height: '1.125rem',
    marginInlineEnd: '-2px',
    padding: 0,
    borderWidth: 0,
    borderStyle: 'none',
    borderRadius: radii.sm,
    backgroundColor: 'transparent',
    color: colors.fgMuted,
    cursor: 'pointer',
    outlineStyle: 'none',
    ':hover': {
      backgroundColor: colors.bgSubtle,
      color: colors.fg,
    },
    ':focus-visible': {
      boxShadow: `0 0 0 2px ${colors.focusRing}`,
    },
  },
  checkMulti: {
    flexShrink: 0,
    width: '1rem',
    height: '1rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: colors.borderStrong,
    borderRadius: radii.sm,
    backgroundColor: colors.inputBg,
    color: colors.accent,
    fontSize: '0.625rem',
    fontWeight: 700,
    lineHeight: 1,
  },
  checkMultiOn: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
})
