import * as stylex from '@stylexjs/stylex'
import { colors, elevation, fonts, radii, space } from '../lib/theme/tokens.stylex'

const fadeUp = stylex.keyframes({
  from: { opacity: 0, transform: 'translateY(22px)' },
  to: { opacity: 1, transform: 'translateY(0)' },
})

const glowBreathe = stylex.keyframes({
  '0%, 100%': { opacity: 1, transform: 'scale(1)' },
  '50%': { opacity: 0.88, transform: 'scale(1.02)' },
})

const floatPill = stylex.keyframes({
  '0%, 100%': { transform: 'translateY(0)' },
  '50%': { transform: 'translateY(-5px)' },
})

export const styles = stylex.create({
  page: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
    backgroundColor: colors.bg,
    position: 'relative',
    overflowX: 'hidden' as const,
  },
  /** Layered wash — reads in light & dark via tokens */
  glow: {
    position: 'absolute',
    inset: 0,
    pointerEvents: 'none',
    backgroundImage: `radial-gradient(ellipse 90% 55% at 50% -15%, ${colors.accentMuted}, transparent 55%),
      radial-gradient(ellipse 50% 35% at 100% 0%, ${colors.neutralMuted}, transparent 50%),
      radial-gradient(ellipse 45% 30% at 0% 100%, ${colors.neutralMuted}, transparent 45%)`,
    zIndex: 0,
    transformOrigin: '50% 30%',
    '@media (prefers-reduced-motion: no-preference)': {
      animationName: glowBreathe,
      animationDuration: '14s',
      animationIterationCount: 'infinite',
      animationTimingFunction: 'ease-in-out',
    },
  },
  nav: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: space.md,
    paddingBlock: space.md,
    paddingInline: space.xl,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: colors.border,
    backgroundColor: colors.bgElevated,
    backdropFilter: 'blur(12px)',
  },
  logo: {
    fontFamily: fonts.sans,
    fontSize: '1rem',
    fontWeight: 700,
    letterSpacing: '-0.03em',
    color: colors.fg,
    textDecoration: 'none',
  },
  logoMuted: {
    fontWeight: 500,
    color: colors.fgMuted,
  },
  navLinks: {
    display: 'flex',
    alignItems: 'center',
    gap: space.lg,
    flexWrap: 'wrap' as const,
  },
  navLink: {
    fontFamily: fonts.sans,
    fontSize: '0.875rem',
    fontWeight: 500,
    color: colors.fgMuted,
    textDecoration: 'none',
    ':hover': {
      color: colors.fg,
    },
  },
  navLinkAccent: {
    color: colors.accent,
    fontWeight: 600,
    ':hover': {
      color: colors.accent,
      opacity: 0.85,
    },
  },
  hero: {
    position: 'relative',
    zIndex: 1,
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBlock: space['2xl'],
    paddingInline: space.lg,
    textAlign: 'center',
    maxWidth: '920px',
    marginInline: 'auto',
    boxSizing: 'border-box',
  },
  kicker: {
    fontFamily: fonts.mono,
    fontSize: '0.75rem',
    fontWeight: 500,
    letterSpacing: '0.14em',
    textTransform: 'uppercase' as const,
    color: colors.accent,
    marginBottom: space.md,
    '@media (prefers-reduced-motion: no-preference)': {
      opacity: 0,
      animationName: fadeUp,
      animationDuration: '0.65s',
      animationFillMode: 'forwards' as const,
      animationDelay: '0ms',
      animationTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)',
    },
  },
  title: {
    fontFamily: fonts.sans,
    fontSize: 'clamp(2.25rem, 5vw, 3.25rem)',
    fontWeight: 800,
    letterSpacing: '-0.045em',
    lineHeight: 1.08,
    color: colors.fg,
    margin: 0,
    marginBottom: space.lg,
    maxWidth: '18ch',
    '@media (prefers-reduced-motion: no-preference)': {
      opacity: 0,
      animationName: fadeUp,
      animationDuration: '0.7s',
      animationFillMode: 'forwards' as const,
      animationDelay: '0.08s',
      animationTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)',
    },
  },
  subtitle: {
    fontFamily: fonts.sans,
    fontSize: '1.125rem',
    lineHeight: 1.6,
    color: colors.fgMuted,
    margin: 0,
    marginBottom: space.lg,
    maxWidth: '42ch',
    '@media (prefers-reduced-motion: no-preference)': {
      opacity: 0,
      animationName: fadeUp,
      animationDuration: '0.7s',
      animationFillMode: 'forwards' as const,
      animationDelay: '0.16s',
      animationTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)',
    },
  },
  pillRow: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: space.sm,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: space.xl,
    '@media (prefers-reduced-motion: no-preference)': {
      opacity: 0,
      animationName: fadeUp,
      animationDuration: '0.6s',
      animationFillMode: 'forwards' as const,
      animationDelay: '0.22s',
    },
  },
  pill: {
    display: 'inline-flex',
    alignItems: 'center',
    paddingInline: space.md,
    paddingBlock: space.xs,
    borderRadius: radii.full,
    fontFamily: fonts.sans,
    fontSize: '0.75rem',
    fontWeight: 600,
    letterSpacing: '0.02em',
    color: colors.fg,
    backgroundColor: colors.bgElevated,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    boxShadow: elevation.input,
    '@media (prefers-reduced-motion: no-preference)': {
      animationName: floatPill,
      animationDuration: '4.5s',
      animationIterationCount: 'infinite',
      animationTimingFunction: 'ease-in-out',
    },
  },
  pillDelay1: {
    '@media (prefers-reduced-motion: no-preference)': {
      animationDelay: '0.4s',
    },
  },
  pillDelay2: {
    '@media (prefers-reduced-motion: no-preference)': {
      animationDelay: '0.8s',
    },
  },
  ctaRow: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: space.md,
    justifyContent: 'center',
    marginBottom: space['2xl'],
    '@media (prefers-reduced-motion: no-preference)': {
      opacity: 0,
      animationName: fadeUp,
      animationDuration: '0.65s',
      animationFillMode: 'forwards' as const,
      animationDelay: '0.3s',
      animationTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)',
    },
  },
  ctaPrimary: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingInline: space.lg,
    paddingBlock: space.md,
    borderRadius: radii.md,
    fontFamily: fonts.sans,
    fontSize: '0.9375rem',
    fontWeight: 600,
    textDecoration: 'none',
    color: colors.accentFg,
    backgroundColor: colors.accent,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.accent,
    minHeight: '40px',
    boxSizing: 'border-box',
    transitionProperty: 'transform, filter, box-shadow',
    transitionDuration: '0.2s',
    transitionTimingFunction: 'ease',
    ':hover': {
      filter: 'brightness(1.06)',
      transform: 'translateY(-2px)',
      boxShadow: elevation.cardHover,
    },
    ':active': {
      transform: 'translateY(0)',
    },
  },
  ctaSecondary: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingInline: space.lg,
    paddingBlock: space.md,
    borderRadius: radii.md,
    fontFamily: fonts.sans,
    fontSize: '0.9375rem',
    fontWeight: 600,
    textDecoration: 'none',
    color: colors.fg,
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    minHeight: '40px',
    boxSizing: 'border-box',
    transitionProperty: 'transform, background-color, box-shadow',
    transitionDuration: '0.2s',
    ':hover': {
      backgroundColor: colors.bgSubtle,
      transform: 'translateY(-2px)',
      boxShadow: elevation.card,
    },
    ':active': {
      transform: 'translateY(0)',
    },
  },
  features: {
    position: 'relative',
    zIndex: 1,
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: space.lg,
    width: '100%',
    maxWidth: '900px',
    marginInline: 'auto',
    paddingInline: space.lg,
    paddingBottom: space['2xl'],
    boxSizing: 'border-box',
  },
  feature: {
    padding: space.lg,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    backgroundColor: colors.bgElevated,
    boxShadow: elevation.card,
    textAlign: 'left' as const,
    boxSizing: 'border-box',
    transitionProperty: 'transform, box-shadow, border-color',
    transitionDuration: '0.22s',
    transitionTimingFunction: 'ease',
    '@media (prefers-reduced-motion: no-preference)': {
      opacity: 0,
      animationName: fadeUp,
      animationDuration: '0.55s',
      animationFillMode: 'forwards' as const,
      animationTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)',
    },
    ':hover': {
      transform: 'translateY(-5px)',
      boxShadow: elevation.cardHover,
      borderColor: colors.borderStrong,
    },
  },
  feature0: {
    '@media (prefers-reduced-motion: no-preference)': {
      animationDelay: '0.42s',
    },
  },
  feature1: {
    '@media (prefers-reduced-motion: no-preference)': {
      animationDelay: '0.52s',
    },
  },
  feature2: {
    '@media (prefers-reduced-motion: no-preference)': {
      animationDelay: '0.62s',
    },
  },
  featureTitle: {
    fontFamily: fonts.sans,
    fontSize: '0.9375rem',
    fontWeight: 600,
    color: colors.fg,
    marginTop: 0,
    marginBottom: space.sm,
    letterSpacing: '-0.02em',
  },
  featureText: {
    fontFamily: fonts.sans,
    fontSize: '0.875rem',
    lineHeight: 1.55,
    color: colors.fgMuted,
    margin: 0,
  },
  footer: {
    position: 'relative',
    zIndex: 1,
    paddingBlock: space.lg,
    paddingInline: space.lg,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    textAlign: 'center',
    fontFamily: fonts.sans,
    fontSize: '0.8125rem',
    color: colors.fgSubtle,
  },
})
