import * as stylex from '@stylexjs/stylex'
import { colors, elevation, fonts, radii, space } from '../lib/theme/tokens.stylex'

const fadeUp = stylex.keyframes({
  from: { opacity: 0, transform: 'translateY(20px)' },
  to: { opacity: 1, transform: 'translateY(0)' },
})

const glowBreathe = stylex.keyframes({
  '0%, 100%': { opacity: 1, transform: 'scale(1)' },
  '50%': { opacity: 0.82, transform: 'scale(1.025)' },
})

const shimmer = stylex.keyframes({
  '0%': { backgroundPosition: '-200% center' },
  '100%': { backgroundPosition: '200% center' },
})

const floatSlow = stylex.keyframes({
  '0%, 100%': { transform: 'translateY(0px)' },
  '50%': { transform: 'translateY(-6px)' },
})

export const styles = stylex.create({
  // ─── Page shell ─────────────────────────────────────────────────────────────
  page: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
    backgroundColor: colors.bg,
    position: 'relative',
    overflowX: 'hidden' as const,
  },
  glow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '75vh',
    pointerEvents: 'none',
    backgroundImage: `radial-gradient(ellipse 80% 60% at 50% -5%, ${colors.accentMuted}, transparent 65%),
      radial-gradient(ellipse 40% 30% at 90% 5%, ${colors.neutralMuted}, transparent 55%),
      radial-gradient(ellipse 35% 25% at 10% 10%, ${colors.neutralMuted}, transparent 50%)`,
    zIndex: 0,
    '@media (prefers-reduced-motion: no-preference)': {
      animationName: glowBreathe,
      animationDuration: '12s',
      animationIterationCount: 'infinite',
      animationTimingFunction: 'ease-in-out',
    },
  },

  // ─── Nav ────────────────────────────────────────────────────────────────────
  nav: {
    position: 'sticky',
    top: 0,
    zIndex: 100,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: space.md,
    paddingBlock: '0.75rem',
    paddingInline: space.xl,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: colors.border,
    backgroundColor: colors.bgElevated,
    backdropFilter: 'blur(16px)',
    WebkitBackdropFilter: 'blur(16px)',
  },
  navLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: space.xl,
  },
  logo: {
    fontFamily: fonts.sans,
    fontSize: '1.0625rem',
    fontWeight: 700,
    letterSpacing: '-0.04em',
    color: colors.fg,
    textDecoration: 'none',
    display: 'flex',
    alignItems: 'center',
    gap: '0.375rem',
  },
  logoMuted: {
    fontWeight: 500,
    color: colors.fgMuted,
  },
  navLinks: {
    display: 'flex',
    alignItems: 'center',
    gap: space.lg,
    '@media (max-width: 680px)': {
      display: 'none',
    },
  },
  navLink: {
    fontFamily: fonts.sans,
    fontSize: '0.875rem',
    fontWeight: 500,
    color: colors.fgMuted,
    textDecoration: 'none',
    transitionProperty: 'color',
    transitionDuration: '0.15s',
    ':hover': {
      color: colors.fg,
    },
  },
  navRight: {
    display: 'flex',
    alignItems: 'center',
    gap: space.md,
  },
  ctaLinkDesktop: {
    '@media (max-width: 680px)': {
      display: 'none',
    },
  },
  mobileMenuBtn: {
    display: 'none',
    '@media (max-width: 680px)': {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '36px',
      height: '36px',
      borderRadius: radii.sm,
      borderWidth: 0,
      backgroundColor: 'transparent',
      color: colors.fgMuted,
      cursor: 'pointer',
      transitionProperty: 'color, background-color',
      transitionDuration: '0.12s',
      ':hover': {
        color: colors.fg,
        backgroundColor: colors.bgSubtle,
      },
    },
  },
  mobileMenu: {
    display: 'none',
    '@media (max-width: 680px)': {
      display: 'flex',
      flexDirection: 'column' as const,
      position: 'absolute' as const,
      top: '100%',
      left: 0,
      right: 0,
      zIndex: 99,
      backgroundColor: colors.bgElevated,
      borderBottomWidth: 1,
      borderBottomStyle: 'solid',
      borderBottomColor: colors.border,
      paddingBlock: space.sm,
      paddingInline: space.xl,
      gap: '2px',
      boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
    },
  },
  mobileMenuLink: {
    fontFamily: fonts.sans,
    fontSize: '0.9375rem',
    fontWeight: 500,
    color: colors.fgMuted,
    textDecoration: 'none',
    paddingBlock: space.sm,
    paddingInline: space.sm,
    borderRadius: radii.sm,
    transitionProperty: 'color, background-color',
    transitionDuration: '0.12s',
    ':hover': {
      color: colors.fg,
      backgroundColor: colors.bgSubtle,
    },
  },
  ghLink: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '2rem',
    height: '2rem',
    borderRadius: radii.md,
    color: colors.fgMuted,
    textDecoration: 'none',
    transitionProperty: 'color, background-color',
    transitionDuration: '0.15s',
    ':hover': {
      color: colors.fg,
      backgroundColor: colors.bgSubtle,
    },
  },

  // ─── Hero ───────────────────────────────────────────────────────────────────
  hero: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    paddingTop: 'clamp(4rem, 10vw, 8rem)',
    paddingBottom: 'clamp(3rem, 6vw, 5rem)',
    paddingInline: space.lg,
    textAlign: 'center',
    maxWidth: '960px',
    marginInline: 'auto',
    width: '100%',
    boxSizing: 'border-box',
  },
  heroBadge: {
    marginBottom: space.lg,
    '@media (prefers-reduced-motion: no-preference)': {
      opacity: 0,
      animationName: fadeUp,
      animationDuration: '0.55s',
      animationFillMode: 'forwards' as const,
      animationDelay: '0ms',
      animationTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)',
    },
  },
  title: {
    fontFamily: fonts.sans,
    fontSize: 'clamp(2.5rem, 6vw, 4rem)',
    fontWeight: 800,
    letterSpacing: '-0.05em',
    lineHeight: 1.06,
    color: colors.fg,
    margin: 0,
    marginBottom: space.lg,
    '@media (prefers-reduced-motion: no-preference)': {
      opacity: 0,
      animationName: fadeUp,
      animationDuration: '0.65s',
      animationFillMode: 'forwards' as const,
      animationDelay: '0.08s',
      animationTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)',
    },
  },
  titleAccent: {
    backgroundImage: `linear-gradient(135deg, ${colors.accent} 0%, ${colors.help} 100%)`,
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    color: 'transparent',
    WebkitTextFillColor: 'transparent',
    backgroundSize: '200% auto',
    '@media (prefers-reduced-motion: no-preference)': {
      animationName: shimmer,
      animationDuration: '4s',
      animationIterationCount: 'infinite',
      animationTimingFunction: 'linear',
    },
  },
  subtitle: {
    fontFamily: fonts.sans,
    fontSize: 'clamp(1rem, 2vw, 1.1875rem)',
    lineHeight: 1.65,
    color: colors.fgMuted,
    margin: 0,
    marginBottom: space.xl,
    maxWidth: '48ch',
    '@media (prefers-reduced-motion: no-preference)': {
      opacity: 0,
      animationName: fadeUp,
      animationDuration: '0.65s',
      animationFillMode: 'forwards' as const,
      animationDelay: '0.16s',
      animationTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)',
    },
  },
  ctaRow: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: space.md,
    justifyContent: 'center',
    marginBottom: space['2xl'],
    '@media (prefers-reduced-motion: no-preference)': {
      opacity: 0,
      animationName: fadeUp,
      animationDuration: '0.6s',
      animationFillMode: 'forwards' as const,
      animationDelay: '0.24s',
      animationTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)',
    },
  },
  ctaLink: {
    textDecoration: 'none',
    display: 'inline-flex',
  },

  // ─── Component showcase strip ────────────────────────────────────────────────
  showcase: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    maxWidth: '900px',
    marginInline: 'auto',
    paddingInline: space.lg,
    paddingBottom: 'clamp(3rem, 6vw, 5rem)',
    boxSizing: 'border-box',
    '@media (prefers-reduced-motion: no-preference)': {
      opacity: 0,
      animationName: fadeUp,
      animationDuration: '0.65s',
      animationFillMode: 'forwards' as const,
      animationDelay: '0.36s',
      animationTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)',
    },
  },
  showcaseInner: {
    padding: space.xl,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    backgroundColor: colors.bgElevated,
    boxShadow: elevation.card,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: space.lg,
    boxSizing: 'border-box',
  },
  showcaseLabel: {
    fontFamily: fonts.mono,
    fontSize: '0.7rem',
    fontWeight: 600,
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
    color: colors.fgSubtle,
  },
  showcaseRow: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    alignItems: 'center',
    gap: space.md,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
  },

  // ─── Stats row ───────────────────────────────────────────────────────────────
  statsSection: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    maxWidth: '900px',
    marginInline: 'auto',
    paddingInline: space.lg,
    paddingBottom: 'clamp(3rem, 6vw, 5rem)',
    boxSizing: 'border-box',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
    gap: space.md,
  },
  statCard: {
    padding: space.lg,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    backgroundColor: colors.bgElevated,
    boxShadow: elevation.card,
    textAlign: 'center' as const,
    boxSizing: 'border-box',
    '@media (prefers-reduced-motion: no-preference)': {
      animationName: floatSlow,
      animationDuration: '5s',
      animationIterationCount: 'infinite',
      animationTimingFunction: 'ease-in-out',
    },
  },
  statCardDelay1: {
    '@media (prefers-reduced-motion: no-preference)': {
      animationDelay: '0.6s',
    },
  },
  statCardDelay2: {
    '@media (prefers-reduced-motion: no-preference)': {
      animationDelay: '1.2s',
    },
  },
  statCardDelay3: {
    '@media (prefers-reduced-motion: no-preference)': {
      animationDelay: '1.8s',
    },
  },
  statNumber: {
    fontFamily: fonts.sans,
    fontSize: 'clamp(1.75rem, 4vw, 2.25rem)',
    fontWeight: 800,
    letterSpacing: '-0.04em',
    color: colors.accent,
    margin: 0,
    lineHeight: 1,
    marginBottom: space.xs,
  },
  statLabel: {
    fontFamily: fonts.sans,
    fontSize: '0.8125rem',
    color: colors.fgMuted,
    margin: 0,
    fontWeight: 500,
  },

  // ─── Features ────────────────────────────────────────────────────────────────
  featuresSection: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    maxWidth: '900px',
    marginInline: 'auto',
    paddingInline: space.lg,
    paddingBottom: 'clamp(4rem, 8vw, 6rem)',
    boxSizing: 'border-box',
  },
  sectionLabel: {
    fontFamily: fonts.mono,
    fontSize: '0.7rem',
    fontWeight: 600,
    letterSpacing: '0.14em',
    textTransform: 'uppercase' as const,
    color: colors.accent,
    marginBottom: space.sm,
    display: 'block',
  },
  sectionTitle: {
    fontFamily: fonts.sans,
    fontSize: 'clamp(1.375rem, 3vw, 1.75rem)',
    fontWeight: 700,
    letterSpacing: '-0.03em',
    color: colors.fg,
    margin: 0,
    marginBottom: space.xl,
  },
  featuresGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(255px, 1fr))',
    gap: space.md,
  },
  featureCard: {
    padding: space.lg,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    backgroundColor: colors.bgElevated,
    boxShadow: elevation.card,
    textAlign: 'left' as const,
    boxSizing: 'border-box',
    transitionProperty: 'transform, box-shadow, border-color',
    transitionDuration: '0.22s',
    transitionTimingFunction: 'ease',
    ':hover': {
      transform: 'translateY(-4px)',
      boxShadow: elevation.cardHover,
      borderColor: colors.borderStrong,
    },
    '@media (prefers-reduced-motion: no-preference)': {
      opacity: 0,
      animationName: fadeUp,
      animationDuration: '0.55s',
      animationFillMode: 'forwards' as const,
      animationTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)',
    },
  },
  featureCard0: { '@media (prefers-reduced-motion: no-preference)': { animationDelay: '0.1s' } },
  featureCard1: { '@media (prefers-reduced-motion: no-preference)': { animationDelay: '0.2s' } },
  featureCard2: { '@media (prefers-reduced-motion: no-preference)': { animationDelay: '0.3s' } },
  featureCard3: { '@media (prefers-reduced-motion: no-preference)': { animationDelay: '0.4s' } },
  featureCard4: { '@media (prefers-reduced-motion: no-preference)': { animationDelay: '0.5s' } },
  featureCard5: { '@media (prefers-reduced-motion: no-preference)': { animationDelay: '0.6s' } },
  featureIcon: {
    width: '2rem',
    height: '2rem',
    borderRadius: radii.md,
    backgroundColor: colors.accentMuted,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: space.md,
    color: colors.accent,
    flexShrink: 0,
  },
  featureTitle: {
    fontFamily: fonts.sans,
    fontSize: '0.9375rem',
    fontWeight: 600,
    letterSpacing: '-0.02em',
    color: colors.fg,
    marginTop: 0,
    marginBottom: space.xs,
  },
  featureText: {
    fontFamily: fonts.sans,
    fontSize: '0.875rem',
    lineHeight: 1.6,
    color: colors.fgMuted,
    margin: 0,
  },

})

export const ctaStyles = stylex.create({
  bottomCta: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    maxWidth: '900px',
    marginInline: 'auto',
    paddingInline: space.lg,
    paddingBottom: space['2xl'],
    boxSizing: 'border-box',
    display: 'flex',
    flexWrap: 'wrap' as const,
    justifyContent: 'center',
    gap: space.sm,
  },
  installBlock: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: space.sm,
    fontFamily: fonts.mono,
    fontSize: '0.8125rem',
    color: colors.fgMuted,
    backgroundColor: colors.bg,
    paddingBlock: '10px',
    paddingLeft: space.md,
    paddingRight: space.sm,
    borderRadius: radii.full,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    marginBottom: space.lg,
    cursor: 'pointer',
    letterSpacing: '-0.01em',
    transitionProperty: 'border-color, box-shadow',
    transitionDuration: '0.15s',
    ':hover': {
      borderColor: colors.borderStrong,
      boxShadow: `0 0 0 3px ${colors.accentMuted}`,
    },
  },
  installPrompt: {
    color: colors.accent,
    fontWeight: 700,
    userSelect: 'none' as const,
  },
  installCmd: {
    color: colors.fg,
    userSelect: 'all' as const,
  },
  installCopyIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '24px',
    height: '24px',
    borderRadius: radii.sm,
    backgroundColor: colors.bgSubtle,
    color: colors.fgSubtle,
    flexShrink: 0,
    transitionProperty: 'color, background-color',
    transitionDuration: '0.12s',
  },
  installCopied: {
    color: colors.success,
  },
  footer: {
    position: 'relative',
    zIndex: 1,
    marginTop: 'auto',
    paddingBlock: space.lg,
    paddingInline: space.xl,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap' as const,
    gap: space.md,
    fontFamily: fonts.sans,
    fontSize: '0.8125rem',
    color: colors.fgSubtle,
  },
  footerLinks: {
    display: 'flex',
    gap: space.lg,
  },
  footerLink: {
    color: colors.fgSubtle,
    textDecoration: 'none',
    fontFamily: fonts.sans,
    fontSize: '0.8125rem',
    transitionProperty: 'color',
    transitionDuration: '0.15s',
    ':hover': {
      color: colors.fgMuted,
    },
  },
})
