import * as stylex from '@stylexjs/stylex'
import { colors, elevation, fonts, radii, space } from '../../lib/theme/tokens.stylex'

export const docPreviewStyles = stylex.create({
  wrap: {
    marginTop: space.xl,
    marginBottom: space['2xl'],
    borderRadius: radii.md,
    overflow: 'visible',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    backgroundColor: colors.bg,
    boxShadow: elevation.card,
  },
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: space.md,
    flexWrap: 'wrap',
    paddingBlock: space.sm,
    paddingInline: space.md,
    backgroundColor: colors.bgElevated,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: colors.border,
  },
  toolbarLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: space.sm,
    minWidth: 0,
  },
  title: {
    fontFamily: fonts.sans,
    fontSize: '0.6875rem',
    fontWeight: 700,
    letterSpacing: '0.1em',
    textTransform: 'uppercase' as const,
    color: colors.fgSubtle,
  },
  toolbarActions: {
    display: 'flex',
    alignItems: 'center',
    gap: space.xs,
    flexShrink: 0,
  },
  toolBtn: {
    fontFamily: fonts.sans,
    fontSize: '0.75rem',
    fontWeight: 600,
    paddingBlock: '6px',
    paddingInline: space.sm,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    backgroundColor: colors.bg,
    color: colors.fgMuted,
    cursor: 'pointer',
    transitionProperty: 'background-color, border-color, color',
    transitionDuration: '0.12s',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    ':hover': {
      backgroundColor: colors.bgSubtle,
      color: colors.fg,
      borderColor: colors.borderStrong,
    },
  },
  toolBtnIcon: {
    paddingInline: '8px',
    minWidth: '2rem',
  },
  toolBtnCopied: {
    color: colors.success,
    borderColor: colors.success,
  },
  previewBody: {
    padding: space.lg,
    backgroundColor: colors.bgSubtle,
    minHeight: '4.5rem',
    boxSizing: 'border-box',
  },
  codeBody: {
    backgroundColor: colors.bgSubtle,
  },
  pre: {
    margin: 0,
    padding: space.lg,
    overflowX: 'auto' as const,
    maxHeight: 'min(70vh, 520px)',
    overflowY: 'auto' as const,
  },
  code: {
    fontFamily: fonts.mono,
    fontSize: '0.8125rem',
    lineHeight: 1.65,
    color: colors.fg,
    whiteSpace: 'pre' as const,
    display: 'block',
    tabSize: 2,
  },
})
